language: generic
sudo: required
services: 
  - docker

  before_install:
    - docker build -t tourafrika/frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true tourafrika/docker-react npm run test -- --coverage

