language: generic
sudo: required
services: 
  - docker

before_install:
  - docker build -t tourafrika/docker-react -f Dockerfile.dev . 

script:
  -  docker run -e CI=true tourafrika/docker-react npm run test

deploy: 
  provider: elasticbeanstalk
  region: "af-south-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-af-south-1-358985322469" 
  bucket_path: "docker"
  skip_cleanup: true
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
